services:
  chatbot:
    image: baolongnguyenmac/chatbot_video_rag:v1
    container_name: ctn_video_chatbot

    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - 5555:7860

    volumes:
      - vector-db:/app/data

# persist data: it's a paid feature in HF Space, so i comment these lines
volumes:
  vector-db: